### ISSUE TITLE
ipfs to WebDAV bridge

### ISSUE THREAD

**Issue by kpmy** [ipfs/apps#31]
Hi. 
For the purpose of easy handling with files in unixfs i'm building a middleware for golang/x/net/webdav server that can provide read/write access to one of ipfs unixfs-dir. 

https://github.com/kpmy/mipfs

For now it can handle basic file operations, there is still some trouble with locks, authorization, file properties, server-side copy/move and large files (maybe this problem can be separated from this project itself).

for testing purposes i have vds with global no registration test service http://d.ocsf.in:6001/ipfs
you can try it with cadaver on linux

`cadaver http://d.ocsf.in:6001/ipfs/` 

also you can get root hash of webdav directory. 

`http://d.ocsf.in:6001/hash`

no guaranties, of course :smile:

**Comment by jbenet** [comment]
Very cool :)

**Comment by kpmy** [comment]
Just in case, is there any analogue of go-ipfs-api.Shell inside go-ipfs, without http api in between?

**Comment by jbenet** [comment]
Yeah, this is the `core` packages. They need some work/love to be nicer,
but you can do everything there.

**Comment by lgierth** [comment]
Actually what your looking for is the Core API, but for go-ipfs it's still a work in progress: https://github.com/ipfs/go-ipfs/issues?utf8=%E2%9C%93&q=milestone%3A%22IPFS%20Core%20API%22%20

**Comment by kpmy** [comment]
It feels great, thnx.

**Comment by kpmy** [comment]
For now I'm using go-ipfs-api, that interacts with ipfs daemon over http rest api. It looks that frequent requests to API become a bottle neck for webdav middleware.

**Comment by kpmy** [comment]
Well, after some optimisations the situation become quite better, but then I put IPFS_REPO on a ram-disk and it was like I'm in heaven. IO does matter.
