### ISSUE TITLE
unixfs builder single leaf optimisation

### ISSUE THREAD

**Issue by pgte** [ipfs/apps#36]
When working on the [JS unixfs-engine](https://github.com/ipfs/js-ipfs-unixfs-engine) to introduce the new DAG builders, the reducer was optimising the reduction of a set of size 1 to that one leaf itself (instead of creating a parent containing only one single link).

But when conducting cross-compat tests against go-ipfs [I had to put this feature behind a flag](https://github.com/ipfs/js-ipfs-unixfs-engine/blob/feat/builders/src/builder/reduce.js#diff-123eec7b4204453dea6837f2fc898477R13) because go-ipfs does not do this.

It would be nice that go-ipfs did this so we can turn this feature flag on by default.

**Comment by Kubuxu** [comment]
cc @whyrusleeping

**Comment by Kubuxu** [comment]
@pgte could you list an example of a operation when this optimization will trigger?
